In [1]:
library(infercnv)

raw_counts_matrix <- "/Users/ugursahin/ProstateCancerEvo_SpatialAnalysis/samples/R1/CNA/R1.pseudobulk.healthy_tumor.tsv"
counts <- read.delim(raw_counts_matrix, header=TRUE, row.names=1, check.names=FALSE)
counts


annotations_f <- "/Users/ugursahin/ProstateCancerEvo_SpatialAnalysis/samples/R1/CNA/R1.ann.V2.tsv"
annotations <- read.delim(annotations_f, header=TRUE, row.names=1, check.names=FALSE)
annotations

gene_order_f <- "/Users/ugursahin/ProstateCancerEvo_SpatialAnalysis/samples/R1/CNA/Xenium.Sapiens.Ref.Ordered.V2.tsv"
gene_order <- read.delim(gene_order_f, header=TRUE, row.names=1, check.names=FALSE)
gene_order


infercnv_obj = CreateInfercnvObject(raw_counts_matrix=counts,
                                    annotations_file=annotations,
                                    delim="\t",
                                    gene_order_file=gene_order,
                                    ref_group_names=c("basal_cell_of_prostate_epithelium","basal_epithelial_cell_of_prostatic_duct"))

        basal_cell_of_prostate_epithelium_pseudoTILE_1
A2ML1    0
AAMP    11
AAR2     3
AARSD1   1
ABAT     0
ABCA1    9
ABCA3    4
ABCA4    0
ABCA7    0
ABCB1    0
ABCB4    0
ABCB6    1
ABCC1    1
ABCC12   0
ABCC2    0
ABCC3    6
ABCC4    0
ABCC6    0
ABCC8    2
ABCC9    0
ABCD1    2
ABCD3    8
ABCD4    1
ABCF3    8
ABCG1    2
ABCG2   28
ABHD11   3
ABHD6   15
ABI3     0
ABI3BP   1
...     ...
ZNF341  0
ZNF346  1
ZNF395  2
ZNF408  2
ZNF410  2
ZNF449  1
ZNF451  3
ZNF469  0
ZNF512  3
ZNF592  4
ZNF608  1
ZNF639  5
ZNF683  0
ZNF687  1
ZNF76   5
ZNF768  3
ZNF8    0
ZNF804A 0
ZNF827  1
ZNF829  0
ZPR1    2
ZSCAN1  0
ZSCAN12 0
ZSCAN16 0
ZSCAN20 1
ZSCAN26 0
ZSWIM6  1
ZUP1    1
ZYG11B  0
ZYX     4
        basal_cell_of_prostate_epithelium_pseudoTILE_10
A2ML1    1
AAMP     2
AAR2     0
AARSD1   1
ABAT     0
ABCA1    0
ABCA3    0
ABCA4    0
ABCA7    1
ABCB1    0
ABCB4    0
ABCB6    3
ABCC1    3
ABCC12   0
ABCC2    0
ABCC3    1
ABCC4    0
ABCC6    0
ABCC8    0
ABCC9    0
ABCD1    0
ABCD3   12
ABCD4    2
ABCF3    7
ABCG1    0
ABCG2   30
ABHD11   0
ABHD6    8
ABI3     0
ABI3BP   0
...     ...
ZNF341  0
ZNF346  0
ZNF395  3
ZNF408  1
ZNF410  2
ZNF449  1
ZNF451  6
ZNF469  0
ZNF512  2
ZNF592  1
ZNF608  0
ZNF639  4
ZNF683  2
ZNF687  3
ZNF76   6
ZNF768  3
ZNF8    0
ZNF804A 0
ZNF827  1
ZNF829  1
ZPR1    2
ZSCAN1  0
ZSCAN12 1
ZSCAN16 4
ZSCAN20 1
ZSCAN26 4
ZSWIM6  1
ZUP1    0
ZYG11B  3
ZYX     1
        basal_cell_of_prostate_epithelium_pseudoTILE_100
A2ML1   0
AAMP    0
AAR2    0
AARSD1  0
ABAT    0
ABCA1   0
ABCA3   0
ABCA4   0
ABCA7   0
ABCB1   0
ABCB4   0
ABCB6   0
ABCC1   0
ABCC12  0
ABCC2   0
ABCC3   0
ABCC4   0
ABCC6   0
ABCC8   0
ABCC9   0
ABCD1   0
ABCD3   0
ABCD4   0
ABCF3   0
ABCG1   0
ABCG2   0
ABHD11  0
ABHD6   0
ABI3    0
ABI3BP  0
...     ...
ZNF341  0
ZNF346  0
ZNF395  0
ZNF408  0
ZNF410  0
ZNF449  0
ZNF451  0
ZNF469  0
ZNF512  0
ZNF592  0
ZNF608  0
ZNF639  0
ZNF683  0
ZNF687  0
ZNF76   0
ZNF768  0
ZNF8    0
ZNF804A 0
ZNF827  0
ZNF829  0
ZPR1    0
ZSCAN1  0
ZSCAN12 0
ZSCAN16 0
ZSCAN20 0
ZSCAN26 0
ZSWIM6  0
ZUP1    0
ZYG11B  0
ZYX     0
        basal_cell_of_prostate_epithelium_pseudoTILE_101
A2ML1    0
AAMP    14
AAR2     1
AARSD1   2
ABAT     0
ABCA1   10
ABCA3    6
ABCA4    2
ABCA7    3
ABCB1    0
ABCB4    0
ABCB6    2
ABCC1    6
ABCC12   0
ABCC2    0
ABCC3    6
ABCC4    0
ABCC6    0
ABCC8    5
ABCC9    0
ABCD1    1
ABCD3   11
ABCD4    0
ABCF3   14
ABCG1    0
ABCG2   41
ABHD11   2
ABHD6   15
ABI3     0
ABI3BP   0
...     ...
ZNF341   0
ZNF346   0
ZNF395   4
ZNF408   0
ZNF410   4
ZNF449   0
ZNF451   3
ZNF469   0
ZNF512   2
ZNF592   2
ZNF608   0
ZNF639  10
ZNF683   1
ZNF687   7
ZNF76    6
ZNF768   4
ZNF8     0
ZNF804A  0
ZNF827   2
ZNF829   0
ZPR1     1
ZSCAN1   0
ZSCAN12  1
ZSCAN16  1
ZSCAN20  2
ZSCAN26  1
ZSWIM6   0
ZUP1     1
ZYG11B   0
ZYX      3
        basal_cell_of_prostate_epithelium_pseudoTILE_102
A2ML1    0
AAMP     9
AAR2     0
AARSD1   0
ABAT     0
ABCA1    3
ABCA3    0
ABCA4    1
ABCA7    1
ABCB1    0
ABCB4    0
ABCB6    1
ABCC1    3
ABCC12   0
ABCC2    0
ABCC3    1
ABCC4    0
ABCC6    0
ABCC8    0
ABCC9    0
ABCD1    1
ABCD3    2
ABCD4    0
ABCF3    5
ABCG1    0
ABCG2   10
ABHD11   0
ABHD6    7
ABI3     0
ABI3BP   0
...     ...
ZNF341  1
ZNF346  2
ZNF395  3
ZNF408  0
ZNF410  5
ZNF449  1
ZNF451  3
ZNF469  0
ZNF512  5
ZNF592  3
ZNF608  1
ZNF639  2
ZNF683  2
ZNF687  3
ZNF76   2
ZNF768  2
ZNF8    1
ZNF804A 0
ZNF827  0
ZNF829  0
ZPR1    0
ZSCAN1  0
ZSCAN12 2
ZSCAN16 1
ZSCAN20 0
ZSCAN26 1
ZSWIM6  0
ZUP1    1
ZYG11B  3
ZYX     3
        basal_cell_of_prostate_epithelium_pseudoTILE_103
A2ML1    0
AAMP     8
AAR2     1
AARSD1   3
ABAT     0
ABCA1    3
ABCA3    3
ABCA4    1
ABCA7    4
ABCB1    0
ABCB4    0
ABCB6    0
ABCC1    6
ABCC12   0
ABCC2    0
ABCC3    5
ABCC4    0
ABCC6    0
ABCC8    3
ABCC9    0
ABCD1    1
ABCD3    8
ABCD4    3
ABCF3   20
ABCG1    3
ABCG2   48
ABHD11   1
ABHD6   19
ABI3     1
ABI3BP   0
...     ...
ZNF341  0
ZNF346  1
ZNF395  6
ZNF408  1
ZNF410  5
ZNF449  3
ZNF451  8
ZNF469  0
ZNF512  6
ZNF592  4
ZNF608  0
ZNF639  5
ZNF683  1
ZNF687  2
ZNF76   3
ZNF768  2
ZNF8    0
ZNF804A 0
ZNF827  3
ZNF829  1
ZPR1    5
ZSCAN1  0
ZSCAN12 2
ZSCAN16 1
ZSCAN20 1
ZSCAN26 2
ZSWIM6  2
ZUP1    4
ZYG11B  2
ZYX     4
        basal_cell_of_prostate_epithelium_pseudoTILE_104
A2ML1    0
AAMP     9
AAR2     3
AARSD1   1
ABAT     0
ABCA1    8
ABCA3    1
ABCA4    1
ABCA7    1
ABCB1    0
ABCB4    0
ABCB6    4
ABCC1    2
ABCC12   1
ABCC2    0
ABCC3    2
ABCC4    0
ABCC6    0
ABCC8    2
ABCC9    2
ABCD1    1
ABCD3   15
ABCD4    3
ABCF3   12
ABCG1    1
ABCG2   47
ABHD11   1
ABHD6   16
ABI3     1
ABI3BP   0
...     ...
ZNF341  1
ZNF346  2
ZNF395  6
ZNF408  1
ZNF410  5
ZNF449  2
ZNF451  6
ZNF469  0
ZNF512  9
ZNF592  2
ZNF608  1
ZNF639  4
ZNF683  1
ZNF687  4
ZNF76   7
ZNF768  6
ZNF8    0
ZNF804A 1
ZNF827  0
ZNF829  1
ZPR1    5
ZSCAN1  0
ZSCAN12 3
ZSCAN16 3
ZSCAN20 0
ZSCAN26 1
ZSWIM6  0
ZUP1    1
ZYG11B  3
ZYX     6
        basal_cell_of_prostate_epithelium_pseudoTILE_105
A2ML1   0
AAMP    0
AAR2    0
AARSD1  0
ABAT    0
ABCA1   0
ABCA3   0
ABCA4   0
ABCA7   0
ABCB1   0
ABCB4   0
ABCB6   0
ABCC1   0
ABCC12  0
ABCC2   0
ABCC3   0
ABCC4   0
ABCC6   0
ABCC8   0
ABCC9   0
ABCD1   0
ABCD3   0
ABCD4   0
ABCF3   0
ABCG1   0
ABCG2   0
ABHD11  0
ABHD6   0
ABI3    0
ABI3BP  0
...     ...
ZNF341  0
ZNF346  0
ZNF395  0
ZNF408  0
ZNF410  0
ZNF449  0
ZNF451  0
ZNF469  0
ZNF512  0
ZNF592  0
ZNF608  0
ZNF639  0
ZNF683  0
ZNF687  0
ZNF76   0
ZNF768  0
ZNF8    0
ZNF804A 0
ZNF827  0
ZNF829  0
ZPR1    0
ZSCAN1  0
ZSCAN12 0
ZSCAN16 0
ZSCAN20 0
ZSCAN26 0
ZSWIM6  0
ZUP1    0
ZYG11B  0
ZYX     0
        basal_cell_of_prostate_epithelium_pseudoTILE_106
A2ML1    0
AAMP    10
AAR2     2
AARSD1   3
ABAT     0
ABCA1    3
ABCA3    3
ABCA4    0
ABCA7    0
ABCB1    0
ABCB4    0
ABCB6    3
ABCC1    9
ABCC12   1
ABCC2    1
ABCC3    7
ABCC4    0
ABCC6    2
ABCC8    5
ABCC9    0
ABCD1    2
ABCD3   16
ABCD4    4
ABCF3   23
ABCG1    3
ABCG2   57
ABHD11   1
ABHD6   24
ABI3     1
ABI3BP   0
...     ...
ZNF341   0
ZNF346   5
ZNF395   3
ZNF408   0
ZNF410  10
ZNF449   1
ZNF451   9
ZNF469   1
ZNF512   7
ZNF592   3
ZNF608   0
ZNF639  10
ZNF683   1
ZNF687   1
ZNF76    6
ZNF768   9
ZNF8     1
ZNF804A  0
ZNF827   8
ZNF829   1
ZPR1     5
ZSCAN1   0
ZSCAN12  1
ZSCAN16  3
ZSCAN20  1
ZSCAN26  2
ZSWIM6   1
ZUP1     2
ZYG11B   3
ZYX     13
        basal_cell_of_prostate_epithelium_pseudoTILE_107 ...
A2ML1    0                                               ...
AAMP     7                                               ...
AAR2     0                                               ...
AARSD1   3                                               ...
ABAT     0                                               ...
ABCA1    2                                               ...
ABCA3    0                                               ...
ABCA4    1                                               ...
ABCA7    0                                               ...
ABCB1    0                                               ...
ABCB4    0                                               ...
ABCB6    0                                               ...
ABCC1    7                                               ...
ABCC12   0                                               ...
ABCC2    0                                               ...
ABCC3    1                                               ...
ABCC4    1                                               ...
ABCC6    0                                               ...
ABCC8    5                                               ...
ABCC9    0                                               ...
ABCD1    2                                               ...
ABCD3    7                                               ...
ABCD4    0                                               ...
ABCF3    9                                               ...
ABCG1    0                                               ...
ABCG2   23                                               ...
ABHD11   1                                               ...
ABHD6    7                                               ...
ABI3     0                                               ...
ABI3BP   0                                               ...
...     ...
ZNF341  0                                                ...
ZNF346  2                                                ...
ZNF395  5                                                ...
ZNF408  1                                                ...
ZNF410  3                                                ...
ZNF449  1                                                ...
ZNF451  5                                                ...
ZNF469  0                                                ...
ZNF512  2                                                ...
ZNF592  1                                                ...
ZNF608  0                                                ...
ZNF639  3                                                ...
ZNF683  0                                                ...
ZNF687  1                                                ...
ZNF76   4                                                ...
ZNF768  6                                                ...
ZNF8    0                                                ...
ZNF804A 0                                                ...
ZNF827  1                                                ...
ZNF829  0                                                ...
ZPR1    2                                                ...
ZSCAN1  0                                                ...
ZSCAN12 1                                                ...
ZSCAN16 0                                                ...
ZSCAN20 1                                                ...
ZSCAN26 1                                                ...
ZSWIM6  1                                                ...
ZUP1    0                                                ...
ZYG11B  2                                                ...
ZYX     0                                                ...
        tumor_cell_markers_pseudoTILE_90 tumor_cell_markers_pseudoTILE_91
A2ML1    1                                0
AAMP    14                                5
AAR2     3                                1
AARSD1   5                                3
ABAT     6                                5
ABCA1   11                                1
ABCA3    3                                4
ABCA4    1                                0
ABCA7    1                                0
ABCB1    0                                0
ABCB4    0                                0
ABCB6    8                                3
ABCC1   46                               10
ABCC12   1                                0
ABCC2    0                                0
ABCC3    0                                0
ABCC4   39                                6
ABCC6    0                                1
ABCC8    3                                1
ABCC9    3                                1
ABCD1    0                                0
ABCD3    4                                2
ABCD4    1                                1
ABCF3    4                                3
ABCG1    2                                2
ABCG2    0                                0
ABHD11   3                                3
ABHD6    1                                3
ABI3     2                                0
ABI3BP   0                                0
...     ...                              ...
ZNF341   2                               1
ZNF346   1                               2
ZNF395  12                               6
ZNF408   0                               2
ZNF410   8                               4
ZNF449   3                               0
ZNF451   4                               2
ZNF469   0                               0
ZNF512  10                               9
ZNF592   8                               1
ZNF608   1                               0
ZNF639  10                               5
ZNF683   2                               0
ZNF687   0                               6
ZNF76    8                               3
ZNF768   7                               2
ZNF8     0                               0
ZNF804A  0                               0
ZNF827   4                               3
ZNF829   3                               0
ZPR1     2                               0
ZSCAN1   0                               0
ZSCAN12  0                               0
ZSCAN16  5                               3
ZSCAN20  2                               1
ZSCAN26  2                               0
ZSWIM6   4                               1
ZUP1     2                               2
ZYG11B   1                               3
ZYX      1                               1
        tumor_cell_markers_pseudoTILE_92 tumor_cell_markers_pseudoTILE_93
A2ML1   0                                0
AAMP    0                                2
AAR2    0                                0
AARSD1  0                                0
ABAT    0                                0
ABCA1   0                                1
ABCA3   0                                0
ABCA4   0                                0
ABCA7   0                                0
ABCB1   0                                0
ABCB4   0                                0
ABCB6   0                                0
ABCC1   1                                2
ABCC12  0                                0
ABCC2   0                                0
ABCC3   0                                0
ABCC4   0                                3
ABCC6   0                                0
ABCC8   0                                0
ABCC9   0                                0
ABCD1   0                                0
ABCD3   0                                0
ABCD4   0                                0
ABCF3   0                                0
ABCG1   0                                0
ABCG2   1                                1
ABHD11  0                                1
ABHD6   0                                1
ABI3    0                                0
ABI3BP  0                                0
...     ...                              ...
ZNF341  0                                0
ZNF346  0                                0
ZNF395  0                                0
ZNF408  0                                0
ZNF410  0                                1
ZNF449  0                                0
ZNF451  0                                1
ZNF469  0                                0
ZNF512  0                                0
ZNF592  0                                0
ZNF608  0                                0
ZNF639  1                                0
ZNF683  0                                0
ZNF687  0                                0
ZNF76   0                                0
ZNF768  0                                0
ZNF8    0                                0
ZNF804A 0                                0
ZNF827  0                                0
ZNF829  0                                0
ZPR1    0                                0
ZSCAN1  0                                0
ZSCAN12 0                                0
ZSCAN16 0                                0
ZSCAN20 0                                0
ZSCAN26 0                                0
ZSWIM6  0                                0
ZUP1    0                                0
ZYG11B  0                                0
ZYX     0                                0
        tumor_cell_markers_pseudoTILE_94 tumor_cell_markers_pseudoTILE_95
A2ML1    0                                0
AAMP    26                                7
AAR2     3                                2
AARSD1   4                                1
ABAT     4                                4
ABCA1    0                                4
ABCA3    2                                2
ABCA4    0                                0
ABCA7    4                                1
ABCB1    0                                0
ABCB4    0                                0
ABCB6    6                                1
ABCC1    8                               18
ABCC12   0                                0
ABCC2    1                                0
ABCC3    0                                1
ABCC4   22                               11
ABCC6    0                                0
ABCC8    1                                2
ABCC9    0                                0
ABCD1    1                                0
ABCD3    3                                3
ABCD4    2                                0
ABCF3    7                                3
ABCG1    0                                1
ABCG2    1                                1
ABHD11   8                                4
ABHD6    2                                1
ABI3     0                                0
ABI3BP   1                                0
...     ...                              ...
ZNF341   1                               0
ZNF346   3                               1
ZNF395   7                               2
ZNF408   1                               0
ZNF410  11                               4
ZNF449   0                               2
ZNF451  12                               2
ZNF469   0                               0
ZNF512   7                               6
ZNF592   2                               6
ZNF608   2                               1
ZNF639   7                               7
ZNF683   1                               1
ZNF687   4                               0
ZNF76   11                               0
ZNF768  25                               6
ZNF8     2                               0
ZNF804A  0                               0
ZNF827   7                               2
ZNF829   0                               0
ZPR1     2                               0
ZSCAN1   0                               0
ZSCAN12  0                               0
ZSCAN16  2                               1
ZSCAN20  0                               0
ZSCAN26  2                               3
ZSWIM6   2                               0
ZUP1     3                               0
ZYG11B   3                               2
ZYX      9                               1
        tumor_cell_markers_pseudoTILE_96 tumor_cell_markers_pseudoTILE_97
A2ML1    0                                1
AAMP    22                                5
AAR2     7                                3
AARSD1   7                                2
ABAT    12                                4
ABCA1   10                                5
ABCA3    5                                3
ABCA4    1                                0
ABCA7    1                                2
ABCB1    0                                0
ABCB4    3                                0
ABCB6    6                                2
ABCC1   28                               19
ABCC12   1                                0
ABCC2    0                                0
ABCC3    0                                0
ABCC4   32                               18
ABCC6    1                                0
ABCC8    1                                1
ABCC9    0                                2
ABCD1    2                                2
ABCD3    6                                1
ABCD4    2                                1
ABCF3    4                                4
ABCG1    3                                1
ABCG2    0                                0
ABHD11  10                                1
ABHD6    4                                3
ABI3     0                                0
ABI3BP   0                                0
...     ...                              ...
ZNF341   3                               0
ZNF346   8                               1
ZNF395  14                               7
ZNF408   3                               0
ZNF410  12                               6
ZNF449   5                               3
ZNF451  12                               5
ZNF469   0                               0

                                                 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_10  basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_100 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_101 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_102 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_103 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_104 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_105 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_106 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_107 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_108 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_109 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_11  basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_110 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_111 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_112 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_113 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_114 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_115 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_116 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_117 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_118 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_119 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_12  basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_120 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_121 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_122 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_123 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_124 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_125 basal_cell_of_prostate_epithelium
basal_cell_of_prostate_epithelium_pseudoTILE_126 basal_cell_of_prostate_epithelium
...                                              ...
tumor_cell_markers_pseudoTILE_72                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_73                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_74                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_75                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_76                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_77                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_78                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_79                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_8                  tumor_cell_markers
tumor_cell_markers_pseudoTILE_80                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_81                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_82                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_83                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_84                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_85                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_86                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_87                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_88                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_89                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_9                  tumor_cell_markers
tumor_cell_markers_pseudoTILE_90                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_91                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_92                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_93                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_94                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_95                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_96                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_97                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_98                 tumor_cell_markers
tumor_cell_markers_pseudoTILE_99                 tumor_cell_markers

         1   9943428   9985501
MMEL1    1     2590639   2633016
ZBTB40   1    22428838  22531157
SLC9A1   1    27098809  27166981
AJAP1    1     4654609   4792534
PTAFR    1    28147166  28193936
TNFRSF1B 1    12166991  12209228
UBE4B    1    10032832  10181239
PLA2G5   1    20028179  20091911
PTPRU    1    29236516  29326813
CASZ1    1    10636604  10796650
GRIK3    1    36795527  37034515
PADI4    1    17308195  17364004
RLF      1    40161387  40240921
GNL2     1    37566816  37595937
MYCBP    1    38862493  38873368
RIMS3    1    40620680  40665682
ZYG11B   1    52726453  52827336
TTC4     1    54715861  54742657
KLF17    1    44118821  44135140
TCEANC2  1    54053584  54112519
GIPC2    1    77979542  78138444
ANGPTL3  1    62597520  62606313
ADGRL4   1    78889764  79282124
PTGFR    1    78303884  78540701
ABCD3    1    94418389  94518666
BCAR3    1    93561741  93847150
BARHL2   1    90711539  90717302
VAV3     1   107571161 107965180
S1PR1    1   101236865 101243713
OLFML3   1   113979391 114035572
...      ... ...       ...
PCBP3    21  45643694  45942454
TMPRSS2  21  41464300  41531116
MX1      21  41420020  41470071
KCNE1    21  34446688  34512214
OLIG2    21  33025935  33029196
OLIG1    21  33070141  33072413
SOD1     21  31659666  31668931
ERG      21  38380027  38661780
TRPM2    21  44350163  44443081
MCM3AP   21  46235133  46286297
GART     21  33503931  33543491
IL10RB   21  33266367  33311420
IFNGR2   21  33403413  33479348
ITGB2    21  44885953  44931989
TIAM1    21  31118416  31559977
SH3BGR   21  39445855  39515506
ICOSLG   21  44215382  44241446
IFNAR2   21  33205282  33265675
IFNAR1   21  33324387  33359864
NRIP1    21  14961235  15065936
CBSL     21   6444869   6467513
APP      21  25880535  26171128
CCT8     21  29055805  29073797
MAP3K7CL 21  29077221  29175889
KCNJ6    21  37607373  38121345
RUNX1    21  34787801  36004667
SLC5A3   21  34073578  34106260
CRYAA    21  43169008  43172810
ABCG1    21  42199689  42304389
DIP2A    21  46458891  46572743

INFO [2025-06-19 20:09:12] ::order_reduce:Start.
INFO [2025-06-19 20:09:12] .order_reduce(): expr and order match.
INFO [2025-06-19 20:09:12] ::process_data:order_reduce:Reduction from positional data, new dimensions (r,c) = 5101,705 Total=14050229 Min=0 Max=2738.
INFO [2025-06-19 20:09:13] num genes removed taking into account provided gene ordering list: 101 = 1.98000392079984% removed.
INFO [2025-06-19 20:09:13] -filtering out cells < 100 or > Inf, removing 1.2766 % of cells
WARN [2025-06-19 20:09:13] Please use "options(scipen = 100)" before running infercnv if you are using the analysis_mode="subclusters" option or you may encounter an error while the hclust is being generated.
INFO [2025-06-19 20:09:13] validating infercnv_obj

In [2]:
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=1, # cutoff=1 works well for Smart-seq2, and cutoff=0.1 works well for 10x Genomics
                             out_dir="/Users/ugursahin/ProstateCancerEvo_SpatialAnalysis/samples/R1/CNA", 
                             cluster_by_groups=TRUE, 
                             denoise=TRUE,
                             HMM=TRUE)

INFO [2025-06-19 20:09:26] ::process_data:Start
INFO [2025-06-19 20:09:26] Checking for saved results.
INFO [2025-06-19 20:09:26]

	STEP 1: incoming data

INFO [2025-06-19 20:09:28]

	STEP 02: Removing lowly expressed genes

INFO [2025-06-19 20:09:28] ::above_min_mean_expr_cutoff:Start
INFO [2025-06-19 20:09:28] Removing 2368 genes from matrix as below mean expr threshold: 1
INFO [2025-06-19 20:09:28] validating infercnv_obj
INFO [2025-06-19 20:09:28] There are 2632 genes and 695 cells remaining in the expr matrix.
INFO [2025-06-19 20:09:28] no genes removed due to min cells/gene filter
INFO [2025-06-19 20:09:29]

	STEP 03: normalization by sequencing depth

INFO [2025-06-19 20:09:29] normalizing counts matrix by depth
INFO [2025-06-19 20:09:29] Computed total sum normalization factor as median libsize: 17989.000000
INFO [2025-06-19 20:09:29] Adding h-spike
INFO [2025-06-19 20:09:29] -hspike modeling of basal_cell_of_prostate_epithelium
INFO [2025-06-19 20:09:44] -hspike modeling of basal_epithelial_cell_of_prostatic_duct
INFO [2025-06-19 20:09:59] validating infercnv_obj
INFO [2025-06-19 20:09:59] normalizing counts matrix by depth
INFO [2025-06-19 20:09:59] Using specified normalization factor: 17989.000000
INFO [2025-06-19 20:10:00]

	STEP 04: log transformation of data

INFO [2025-06-19 20:10:00] transforming log2xplus1()
INFO [2025-06-19 20:10:00] -mirroring for hspike
INFO [2025-06-19 20:10:00] transforming log2xplus1()
INFO [2025-06-19 20:10:02]

	STEP 08: removing average of reference data (before smoothing)

INFO [2025-06-19 20:10:02] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2025-06-19 20:10:02] subtracting mean(normal) per gene per cell across all data
INFO [2025-06-19 20:10:02] -subtracting expr per gene, use_bounds=TRUE
INFO [2025-06-19 20:10:03] -mirroring for hspike
INFO [2025-06-19 20:10:03] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2025-06-19 20:10:03] subtracting mean(normal) per gene per cell across all data
INFO [2025-06-19 20:10:03] -subtracting expr per gene, use_bounds=TRUE
INFO [2025-06-19 20:10:05]

	STEP 09: apply max centered expression threshold: 3

INFO [2025-06-19 20:10:05] ::process_data:setting max centered expr, threshold set to: +/-:  3
INFO [2025-06-19 20:10:05] -mirroring for hspike
INFO [2025-06-19 20:10:05] ::process_data:setting max centered expr, threshold set to: +/-:  3
INFO [2025-06-19 20:10:07]

	STEP 10: Smoothing data per cell by chromosome

INFO [2025-06-19 20:10:07] smooth_by_chromosome: chr: 1
INFO [2025-06-19 20:10:08] smooth_by_chromosome: chr: 2
INFO [2025-06-19 20:10:08] smooth_by_chromosome: chr: 3
INFO [2025-06-19 20:10:08] smooth_by_chromosome: chr: 4
INFO [2025-06-19 20:10:08] smooth_by_chromosome: chr: 5
INFO [2025-06-19 20:10:09] smooth_by_chromosome: chr: 6
INFO [2025-06-19 20:10:09] smooth_by_chromosome: chr: 7
INFO [2025-06-19 20:10:09] smooth_by_chromosome: chr: X
INFO [2025-06-19 20:10:10] smooth_by_chromosome: chr: 8
INFO [2025-06-19 20:10:10] smooth_by_chromosome: chr: 9
INFO [2025-06-19 20:10:10] smooth_by_chromosome: chr: 11
INFO [2025-06-19 20:10:10] smooth_by_chromosome: chr: 10
INFO [2025-06-19 20:10:11] smooth_by_chromosome: chr: 12
INFO [2025-06-19 20:10:11] smooth_by_chromosome: chr: 13
INFO [2025-06-19 20:10:11] smooth_by_chromosome: chr: 14
INFO [2025-06-19 20:10:11] smooth_by_chromosome: chr: 15
INFO [2025-06-19 20:10:12] smooth_by_chromosome: chr: 16
INFO [2025-06-19 20:10:12] smooth_by_chromosome: chr: 17
INFO [2025-06-19 20:10:12] smooth_by_chromosome: chr: 18
INFO [2025-06-19 20:10:12] smooth_by_chromosome: chr: 20
INFO [2025-06-19 20:10:13] smooth_by_chromosome: chr: 19
INFO [2025-06-19 20:10:13] smooth_by_chromosome: chr: Y
INFO [2025-06-19 20:10:13] smooth_by_chromosome: chr: 22
INFO [2025-06-19 20:10:13] smooth_by_chromosome: chr: 21
INFO [2025-06-19 20:10:14] -mirroring for hspike
INFO [2025-06-19 20:10:14] smooth_by_chromosome: chr: chrA
INFO [2025-06-19 20:10:14] smooth_by_chromosome: chr: chr_0
INFO [2025-06-19 20:10:14] smooth_by_chromosome: chr: chr_B
INFO [2025-06-19 20:10:14] smooth_by_chromosome: chr: chr_0pt5
INFO [2025-06-19 20:10:14] smooth_by_chromosome: chr: chr_C
INFO [2025-06-19 20:10:14] smooth_by_chromosome: chr: chr_1pt5
INFO [2025-06-19 20:10:15] smooth_by_chromosome: chr: chr_D
INFO [2025-06-19 20:10:15] smooth_by_chromosome: chr: chr_2pt0
INFO [2025-06-19 20:10:15] smooth_by_chromosome: chr: chr_E
INFO [2025-06-19 20:10:15] smooth_by_chromosome: chr: chr_3pt0
INFO [2025-06-19 20:10:15] smooth_by_chromosome: chr: chr_F
INFO [2025-06-19 20:10:18]

	STEP 11: re-centering data across chromosome after smoothing

INFO [2025-06-19 20:10:18] ::center_smooth across chromosomes per cell
INFO [2025-06-19 20:10:18] -mirroring for hspike
INFO [2025-06-19 20:10:18] ::center_smooth across chromosomes per cell
INFO [2025-06-19 20:10:20]

	STEP 12: removing average of reference data (after smoothing)

INFO [2025-06-19 20:10:20] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2025-06-19 20:10:20] subtracting mean(normal) per gene per cell across all data
INFO [2025-06-19 20:10:20] -subtracting expr per gene, use_bounds=TRUE
INFO [2025-06-19 20:10:20] -mirroring for hspike
INFO [2025-06-19 20:10:20] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2025-06-19 20:10:20] subtracting mean(normal) per gene per cell across all data
INFO [2025-06-19 20:10:21] -subtracting expr per gene, use_bounds=TRUE
INFO [2025-06-19 20:10:23]

	STEP 14: invert log2(FC) to FC

INFO [2025-06-19 20:10:23] invert_log2(), computing 2^x
INFO [2025-06-19 20:10:23] -mirroring for hspike
INFO [2025-06-19 20:10:23] invert_log2(), computing 2^x
INFO [2025-06-19 20:10:25]

	STEP 15: computing tumor subclusters via leiden

INFO [2025-06-19 20:10:25] define_signif_tumor_subclusters(p_val=0.1
INFO [2025-06-19 20:10:25] define_signif_tumor_subclusters(), tumor: tumor_cell_markers
INFO [2025-06-19 20:10:25] Setting auto leiden resolution for tumor_cell_markers to 0.095421

Warning message:
"Data is of class matrix. Coercing to dgCMatrix."
Finding variable features for layer counts

Centering and scaling data matrix

PC_ 1
Positive:  FLOT2, MYO1D, RHOT1, PHF12, TRAF4, TEFM, NF1, TMEM98, NEK8, LIG3
	   UNC119, SLFN5, POLDIP2, TMEM97, ACACA, SPECC1, ULK2, TADA2A, ALDH3A2, SHMT1
	   FLII, ALKBH5, SYNRG, TOM1L2, HNF1B, SREBF1, MRPL45, RASD1, SRCIN1, FLCN
Negative:  GSTM1, GSTM3, SORT1, CELSR2, STRIP1, SLC30A7, CDC14A, RBM15, SLC16A4, DPYD
	   LRIF1, ABCD3, WDR77, GCLM, RAP1A, BCAR3, DDX20, EVI5, CTTNBP2NL, MOV10
	   TGFBR3, RHOC, ZNF326, SLC16A1, RSBN1, GBP1, NRAS, ATP1A1, ODF2L, CD58
PC_ 2
Positive:  ABCA1, FKTN, KLF4, NIPSNAP3A, CTNNAL1, ECPAS, INVS, SNX30, NR4A3, FKBP15
	   ALAD, ALG2, ASTN2, PAPPA, TNC, PTGS1, RC3H2, NEK6, TGFBR1, PBX3
	   XPA, RALGPS1, GNAI1, POR, RHBDD2, CACNA2D1, CDK9, GTF2I, SLC25A40, NCBP1
Negative:  PTCD3, IMMT, XPO1, RTN4, SPTBN1, PNPT1, REL, ATOH8, EHBP1, KDM3A
	   BCL11A, ACYP2, HTRA2, LGALSL, MSH6, RMND5A, APLF, CCT7, GFPT1, DCTN1
	   MSH2, RGPD1, EPCAM, CYTOR, EIF2AK3, HMGCR, GCNT4, CRIPT, HEXB, IQGAP2
PC_ 3
Positive:  ITGB6, BAZ2B, CD302, RBMS1, MMADHC, ACVR2A, DPP4, HNMT, MCM6, IFIH1
	   R3HDM1, COBLL1, PLEKHB2, STK39, POTEI, NOSTRIN, POTEF, SSB, UBR3, TLK1
	   RAB6C, ITGA6, PDK1, MAP3K20, ERCC3, NIFK, INHBB, CBWD2, PAX8, RGPD8
Negative:  HECTD4, PTPN11, TRAFD1, TPCN1, ALDH2, CUX2, RBM19, PHETA1, ATXN2, ATP2A2
	   ANKRD13A, TBX3, RFC5, KCTD10, HSPB8, ACACB, PRKAB1, GCN1, UNG, PXN
	   CORO1C, MSI1, P2RX4, SART3, MLXIP, PWP1, ZCCHC8, VPS37B, MTERF2, MPHOSPH9
PC_ 4
Positive:  CCT6A, LANCL2, GUSB, EGFR, TBRG4, NSUN5, SNHG15, PURB, BCL7B, ZMIZ2
	   OGDH, TBL2, URGCP, ABHD11, BLVRA, HOXA5, EPDR1, CBX3, HOXA13, HOXA9
	   CYCS, SCRN1, HOXA10, LIMK1, CDCA7L, MACC1, GTF2I, TWIST1, HDAC9, RHBDD2
Negative:  GLB1, CMTM8, MLH1, EPM2AIP1, PDCD6IP, TGFBR2, CTDSPL, RBMS3, OXSM, TOP2B
	   MYD88, THRB, KAT2B, OXSR1, RAB5A, SATB1, SH3BP5, EIF1B, NR2C2, XPC
	   CTNNB1, TMEM43, IQSEC1, VIPR1, RAF1, MKRN2, SEC13, VHL, CAMK1, THUMPD3
PC_ 5
Positive:  FOXO4, IGBP1, MED12, AR, MSN, ZC4H2, SPIN3, APEX2, PHF8, HUWE1
	   HSD17B10, HSPG2, CDC42, ECE1, ZBTB40, PINK1, SMC1A, KDM1A, PLP2, NBL1
	   TCEA3, TFE3, FUCA1, PITHD1, CLIC4, GALE, EMC1, PIM2, MTFR1L, STMN1
Negative:  CMTM8, TGFBR2, RBMS3, GLB1, OXSM, TOP2B, PDCD6IP, THRB, KAT2B, RAB5A
	   SATB1, EPM2AIP1, SH3BP5, NR2C2, XPC, MLH1, TMEM43, IQSEC1, RAF1, MKRN2
	   CTDSPL, SEC13, VHL, CAMK1, THUMPD3, MYD88, OXSR1, EIF1B, CTNNB1, VIPR1

Computing nearest neighbor graph

Computing SNN

INFO [2025-06-19 20:10:26] define_signif_tumor_subclusters(), tumor: basal_cell_of_prostate_epithelium
INFO [2025-06-19 20:10:26] Setting auto leiden resolution for basal_cell_of_prostate_epithelium to 0.0570262

Warning message:
"Data is of class matrix. Coercing to dgCMatrix."
Finding variable features for layer counts

Centering and scaling data matrix

PC_ 1
Positive:  MAPK10, WDFY3, PTPN13, HNRNPD, BMP2K, AFF1, ANXA3, KLHL8, NPNT, TET2
	   SLC39A8, CISD2, NFKB1, TBCK, PKD2, UBE2D3, SDAD1, PPP3CA, HERC6, SMARCAD1
	   PAPSS1, NAP1L5, ABCG2, EIF4E, BMPR1B, LEF1, NAAA, CASP6, PARM1, ANKRD17
Negative:  HOXB5, HOXB6, HOXB4, HOXB7, SNX11, HOXB9, CBX1, HOXB13, NFE2L1, PHB
	   ITGA3, KPNB1, LRRC59, PPP1R9B, ABCC3, CDC27, ANKRD40, MAPT, NME1, HEXIM1
	   STXBP4, TMEM100, GHITM, TSPAN14, WAPL, EFTUD2, BMPR1A, PRXL2A, COIL, PRPS2
PC_ 2
Positive:  IL6ST, MTREX, MAP3K1, DHX29, GPBP1, CCNO, PART1, ITGA2, ZSWIM6, PELO
	   GHR, KIF2A, PRKAA1, IPO11, LIFR, RNF180, TRIM23, SKP2, PIK3R1, PRLR
	   CDK7, BRIX1, OCLN, SMN2, RAI14, PTGFRN, IGSF3, CD58, TENT5C, PHGDH
Negative:  CYLD, HEATR3, RBL2, SIAH1, AKTIP, CRNDE, FTO, GNAO1, AMFR, VPS35
	   NUDT21, NUP93, RSPRY1, CFAP20, POLR2C, CSNK2A2, PYCARD, CCDC113, NDRG4, CNOT1
	   CBFB, HSF4, FUS, E2F4, SMPD3, DDX19A, RIPOR1, CDH3, WWP2, NFATC3
PC_ 3
Positive:  SUGP2, YJEFN3, PEPD, UPF1, GRAMD1A, KLHL26, DMKN, KXD1, PSENEN, GDF15
	   YIF1B, KCNK6, ACTN4, PIK3R2, SIRT2, PAK4, CCDC124, DYRK1B, FBL, MAP1S
	   FCGBP, SLC35E1, RAB8A, AP1M1, AKAP8, AKT2, BRD4, NOTCH3, GIPC1, ADGRL1
Negative:  PPIC, SRFBP1, GRAMD2B, TNFAIP8, ALDH7A1, DMXL1, LMNB1, PGGT1B, SLC12A2, YTHDC2
	   RAPGEF6, NREP, SLC22A5, FER, IRF1, PAM, RAD50, SHROOM1, ERAP1, ZCCHC10
	   ARRDC3, HSPA4, VPS35, PYCARD, FUS, SIAH1, BCKDK, VDAC1, HEATR3, RASA1
PC_ 4
Positive:  CYTH2, BAX, TRPM4, RUVBL2, GYS1, GRWD1, PIH1D1, CARD8, MEIS3, PRRG2
	   RRAS, CCDC9, ARHGAP35, IRF3, SLC1A5, PRMT1, STRN4, AP2A1, CALM3, EPAS1
	   PTOV1, PIGF, PREPL, CRIPT, LRPPRC, NUP62, IRF2BP1, EPCAM, MAP4K3, KCNC3
Negative:  SERPINA3, SERPINA5, LGMN, DICER1, ATXN3, WARS, MEG3, YY1, FBLN5, DYNC1H1
	   CINP, RCOR1, RPS6KA5, TC2N, ZFYVE21, NRDE2, AKT1, SPATA7, MTA1, SEL1L
	   DIO2, GSTZ1, IRF2BPL, ERG28, JDP2, PGF, YLPM1, ABCD4, ZNF410, PNMA1
PC_ 5
Positive:  YWHAZ, VPS13B, UBR5, GRHL2, STK3, FZD6, RIDA, ANGPT1, LAPTM4B, NUDCD1
	   TSPYL5, UTP23, MAL2, SDC2, DEPTOR, PTDSS1, SQLE, NBN, TRIB1, OSGIN2
	   LRATD2, RIPK2, PCAT1, RMDN1, MYC, WWP1, PVT1, SNX16, EFR3A, ZBTB10
Negative:  UQCC1, GSS, RBM12, MAP1LC3A, ITCH, NORAD, AHCY, AAR2, SAMHD1, CDK5RAP1
	   NOL4L, SRC, ASXL1, VSTM2L, NPTN, HEXA, CD276, PLAGL2, MAP2K5, PKM
	   SMAD3, TM9SF4, LOXL1, TTI1, MAP2K1, BCL2L1, RAB11A, PML, PYGB, SLC24A1

Computing nearest neighbor graph

Computing SNN

INFO [2025-06-19 20:10:26] define_signif_tumor_subclusters(), tumor: basal_epithelial_cell_of_prostatic_duct
INFO [2025-06-19 20:10:26] Setting auto leiden resolution for basal_epithelial_cell_of_prostatic_duct to 0.101075

Warning message:
"Data is of class matrix. Coercing to dgCMatrix."
Finding variable features for layer counts

Centering and scaling data matrix

PC_ 1
Positive:  PRXL2A, TSPAN14, GHITM, PPIF, WAPL, ZMIZ1, BMPR1A, KCNMA1, VDAC2, MMRN2
	   VCL, CAMK2G, MYOF, DNAJC9, ECD, P4HA1, IDE, DNAJB12, CPEB3, FRA10AC1
	   BTAF1, NOC3L, GLUD1, CRTAC1, PCBD1, LIPA, HOXB9, GOT1, HOXB6, HOXB7
Negative:  PTGS1, RC3H2, NEK6, ASTN2, PBX3, TBCK, PAPSS1, LEF1, NPNT, PAPPA
	   RALGPS1, TET2, CASP6, CDK9, CISD2, TNC, UBE2D3, CAMK2D, ENG, NFKB1
	   GOLGA2, SYNPO2, ALAD, SLC39A8, ZBTB10, ZC2HC1A, SNX16, ZER1, FKBP15, ZFHX4
PC_ 2
Positive:  MEIS3, CCDC9, ARHGAP35, CARD8, GRWD1, SLC1A5, CYTH2, BAX, STRN4, GYS1
	   CALM3, IRF2BP1, RUVBL2, DMWD, TRPM4, VASP, PIH1D1, ERCC1, ERCC2, PRRG2
	   RRAS, PPP1R37, TOMM40, IRF3, NECTIN2, PRMT1, BCAM, BCL3, AP2A1, PVR
Negative:  TBK1, DPY19L2, RASSF3, GNS, PPM1H, TBC1D30, MON2, LIMK1, TMBIM4, ABHD11
	   RHBDD2, POR, GTF2I, CDK4, CAND1, GNAI1, CACNA2D1, TSPAN31, TBL2, SLC25A40
	   R3HDM2, MDM1, SRI, STEAP4, STEAP1, NUP107, SHMT2, BCL7B, DUSP6, KITLG
PC_ 3
Positive:  REST, HOPX, CLOCK, NOA1, KIT, ATP10D, FIP1L1, SPATA18, TEC, TMEM33
	   POLR2B, N4BP2, UGT2B7, UGDH, NPFFR2, STIM2, RBPJ, ANKRD17, SOD3, PARM1
	   PPARGC1A, NAAA, ADGRA3, SDAD1, SLIT2, ANXA3, CD38, BMP2K, CPEB2, HNRNPD
Negative:  FBP1, NINJ1, GADD45G, XPA, PTCH1, TDRD7, NCBP1, SEMA4D, TGFBR1, CKS2
	   SPIN1, ALG2, CTSL, NR4A3, DAPK1, INVS, GNAQ, NIPSNAP3A, VPS13A, ABCA1
	   RORB, ZFAND5, FKTN, CEMIP2, KLF4, TRPM3, CTNNAL1, TJP2, ECPAS, ALDH1B1
PC_ 4
Positive:  PARK7, PER3, ERRFI1, VAMP3, CLSTN1, LZIC, THAP3, UBE4B, PGD, ZBTB48
	   CASZ1, TARDBP, EXOSC10, AJAP1, MTOR, NPPA, LRRC47, KIAA2013, MFN2, MIIP
	   PDPN, WRAP73, CASP9, TNFRSF14, DDI2, PLEKHM2, PRKCZ, FBXO42, SDHB, DVL1
Negative:  SEMA4C, CNNM3, MITD1, SNRNP200, TXNDC9, PROM2, MAP4K4, EIF2AK3, IL1R1, CYTOR
	   IL1RL2, IL1RL1, RGPD1, RMND5A, IL18R1, KDM3A, IMMT, PTCD3, ATOH8, POU3F3
	   HTRA2, APLF, LGALSL, GFPT1, DCTN1, EHBP1, CCT7, RANBP2, XPO1, REL
PC_ 5
Positive:  PHETA1, CUX2, ALDH2, ATXN2, TRAFD1, ANKRD13A, ATP2A2, HECTD4, KCTD10, PTPN11
	   ACACB, TPCN1, UNG, CORO1C, RBM19, SART3, PWP1, TBX3, MTERF2, CKAP4
	   RFC5, WASHC4, TXNRD1, HSPB8, NT5DC3, WASHC3, PRKAB1, APAF1, GCN1, BAG6
Negative:  SF3A1, ASCC2, DRG1, NF2, NIPSNAP1, EIF4ENIF1, NEFH, PRR14L, AP1B1, SLC5A1
	   GAS2L1, EWSR1, RTCB, XBP1, CHEK2, MCM5, PITPNB, APOL6, MIAT, GGT1
	   APOL3, SNRPD3, SPECC1L, APOL2, DERL3, SMARCB1, APOL1, BCR, TOP3B, MYH9

Computing nearest neighbor graph

Computing SNN

INFO [2025-06-19 20:10:26] -mirroring for hspike
INFO [2025-06-19 20:10:26] define_signif_tumor_subclusters(p_val=0.1
INFO [2025-06-19 20:10:26] define_signif_tumor_subclusters(), tumor: spike_tumor_cell_basal_cell_of_prostate_epithelium
INFO [2025-06-19 20:10:26] cut tree into: 1 groups
INFO [2025-06-19 20:10:26] -processing spike_tumor_cell_basal_cell_of_prostate_epithelium,spike_tumor_cell_basal_cell_of_prostate_epithelium_s1
INFO [2025-06-19 20:10:26] define_signif_tumor_subclusters(), tumor: spike_tumor_cell_basal_epithelial_cell_of_prostatic_duct
INFO [2025-06-19 20:10:26] cut tree into: 1 groups
INFO [2025-06-19 20:10:26] -processing spike_tumor_cell_basal_epithelial_cell_of_prostatic_duct,spike_tumor_cell_basal_epithelial_cell_of_prostatic_duct_s1
INFO [2025-06-19 20:10:26] define_signif_tumor_subclusters(), tumor: simnorm_cell_basal_cell_of_prostate_epithelium
INFO [2025-06-19 20:10:27] cut tree into: 1 groups
INFO [2025-06-19 20:10:27] -processing simnorm_cell_basal_cell_of_prostate_epithelium,simnorm_cell_basal_cell_of_prostate_epithelium_s1
INFO [2025-06-19 20:10:27] define_signif_tumor_subclusters(), tumor: simnorm_cell_basal_epithelial_cell_of_prostatic_duct
INFO [2025-06-19 20:10:27] cut tree into: 1 groups
INFO [2025-06-19 20:10:27] -processing simnorm_cell_basal_epithelial_cell_of_prostatic_duct,simnorm_cell_basal_epithelial_cell_of_prostatic_duct_s1
INFO [2025-06-19 20:10:29] ::plot_cnv:Start
INFO [2025-06-19 20:10:29] ::plot_cnv:Current data dimensions (r,c)=2632,695 Total=1832833.23760121 Min=0.342993304306495 Max=8.70781916655213.
INFO [2025-06-19 20:10:29] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2025-06-19 20:10:29] plot_cnv(): auto thresholding at: (0.763415 , 1.240513)
INFO [2025-06-19 20:10:29] plot_cnv_observation:Start
INFO [2025-06-19 20:10:29] Observation data size: Cells= 185 Genes= 2632
INFO [2025-06-19 20:10:29] clustering observations via method: ward.D
INFO [2025-06-19 20:10:29] Number of cells in group(1) is 93
INFO [2025-06-19 20:10:29] group size being clustered:  93,2632
INFO [2025-06-19 20:10:29] Number of cells in group(2) is 30
INFO [2025-06-19 20:10:29] group size being clustered:  30,2632
INFO [2025-06-19 20:10:29] Number of cells in group(3) is 30
INFO [2025-06-19 20:10:29] group size being clustered:  30,2632
INFO [2025-06-19 20:10:29] Number of cells in group(4) is 19
INFO [2025-06-19 20:10:29] group size being clustered:  19,2632
INFO [2025-06-19 20:10:29] Number of cells in group(5) is 7
INFO [2025-06-19 20:10:29] group size being clustered:  7,2632
INFO [2025-06-19 20:10:29] Number of cells in group(6) is 2
INFO [2025-06-19 20:10:29] group size being clustered:  2,2632
INFO [2025-06-19 20:10:29] Number of cells in group(7) is 2
INFO [2025-06-19 20:10:29] group size being clustered:  2,2632
INFO [2025-06-19 20:10:29] Number of cells in group(8) is 1
INFO [2025-06-19 20:10:29] Skipping group: 8, since less than 2 entries
INFO [2025-06-19 20:10:29] Number of cells in group(9) is 1
INFO [2025-06-19 20:10:29] Skipping group: 9, since less than 2 entries
INFO [2025-06-19 20:10:29] plot_cnv_observation:Writing observation groupings/color.
INFO [2025-06-19 20:10:29] plot_cnv_observation:Done writing observation groupings/color.
INFO [2025-06-19 20:10:29] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2025-06-19 20:10:29] plot_cnv_observation:Done writing observation heatmap thresholds.
INFO [2025-06-19 20:10:29] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2025-06-19 20:10:29] Quantiles of plotted data range: 0.763415183049742,0.931942102776112,1,1.07488226858281,1.24051348415762
INFO [2025-06-19 20:10:29] plot_cnv_references:Start
INFO [2025-06-19 20:10:29] Reference data size: Cells= 510 Genes= 2632
INFO [2025-06-19 20:10:29] plot_cnv_references:Number reference groups= 22
INFO [2025-06-19 20:10:29] plot_cnv_references:Plotting heatmap.
INFO [2025-06-19 20:10:29] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2025-06-19 20:10:29] Quantiles of plotted data range: 0.763415183049742,0.976177604461326,1,1.02415223872586,1.24051348415762
INFO [2025-06-19 20:10:31] ::plot_cnv:Start
INFO [2025-06-19 20:10:31] ::plot_cnv:Current data dimensions (r,c)=2632,695 Total=1832833.23760121 Min=0.342993304306495 Max=8.70781916655213.
INFO [2025-06-19 20:10:31] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2025-06-19 20:10:31] plot_cnv(): auto thresholding at: (0.763415 , 1.240513)
INFO [2025-06-19 20:10:31] plot_cnv_observation:Start
INFO [2025-06-19 20:10:31] Observation data size: Cells= 185 Genes= 2632
INFO [2025-06-19 20:10:31] plot_cnv_observation:Writing observation groupings/color.
INFO [2025-06-19 20:10:31] plot_cnv_observation:Done writing observation groupings/color.
INFO [2025-06-19 20:10:31] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2025-06-19 20:10:31] plot_cnv_observation:Done writing observation heatmap thresholds.
INFO [2025-06-19 20:10:32] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2025-06-19 20:10:32] Quantiles of plotted data range: 0.763415183049742,0.931942102776112,1,1.07488226858281,1.24051348415762
INFO [2025-06-19 20:10:32] plot_cnv_references:Start
INFO [2025-06-19 20:10:32] Reference data size: Cells= 510 Genes= 2632
INFO [2025-06-19 20:10:32] plot_cnv_references:Number reference groups= 2
INFO [2025-06-19 20:10:32] plot_cnv_references:Plotting heatmap.
INFO [2025-06-19 20:10:32] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2025-06-19 20:10:32] Quantiles of plotted data range: 0.763415183049742,0.976177604461326,1,1.02415223872586,1.24051348415762
INFO [2025-06-19 20:10:32]

	STEP 17: HMM-based CNV prediction

INFO [2025-06-19 20:10:32] predict_CNV_via_HMM_on_tumor_subclusters
INFO [2025-06-19 20:10:34] -done predicting CNV based on initial tumor subclusters
INFO [2025-06-19 20:10:34] get_predicted_CNV_regions(subcluster)
INFO [2025-06-19 20:10:34] -processing cell_group_name: tumor_cell_markers.tumor_cell_markers_s2, size: 93
INFO [2025-06-19 20:10:35] -processing cell_group_name: tumor_cell_markers.tumor_cell_markers_s3, size: 30
INFO [2025-06-19 20:10:36] -processing cell_group_name: tumor_cell_markers.tumor_cell_markers_s5, size: 30
INFO [2025-06-19 20:10:37] -processing cell_group_name: tumor_cell_markers.tumor_cell_markers_s4, size: 19
INFO [2025-06-19 20:10:38] -processing cell_group_name: tumor_cell_markers.tumor_cell_markers_s1, size: 7
INFO [2025-06-19 20:10:38] -processing cell_group_name: tumor_cell_markers.tumor_cell_markers_s6, size: 2
INFO [2025-06-19 20:10:39] -processing cell_group_name: tumor_cell_markers.tumor_cell_markers_s7, size: 2
INFO [2025-06-19 20:10:40] -processing cell_group_name: tumor_cell_markers.tumor_cell_markers_s8, size: 1
INFO [2025-06-19 20:10:41] -processing cell_group_name: tumor_cell_markers.tumor_cell_markers_s9, size: 1
INFO [2025-06-19 20:10:41] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s5, size: 90
INFO [2025-06-19 20:10:42] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s7, size: 89
INFO [2025-06-19 20:10:43] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s1, size: 46
INFO [2025-06-19 20:10:44] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s4, size: 31
INFO [2025-06-19 20:10:44] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s2, size: 21
INFO [2025-06-19 20:10:45] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s8, size: 13
INFO [2025-06-19 20:10:46] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s12, size: 12
INFO [2025-06-19 20:10:47] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s6, size: 8
INFO [2025-06-19 20:10:47] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s11, size: 8
INFO [2025-06-19 20:10:48] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s9, size: 7
INFO [2025-06-19 20:10:49] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s10, size: 6
INFO [2025-06-19 20:10:50] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s13, size: 3
INFO [2025-06-19 20:10:50] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s14, size: 2
INFO [2025-06-19 20:10:51] -processing cell_group_name: basal_cell_of_prostate_epithelium.basal_cell_of_prostate_epithelium_s3, size: 1
INFO [2025-06-19 20:10:52] -processing cell_group_name: basal_epithelial_cell_of_prostatic_duct.basal_epithelial_cell_of_prostatic_duct_s3, size: 86
INFO [2025-06-19 20:10:53] -processing cell_group_name: basal_epithelial_cell_of_prostatic_duct.basal_epithelial_cell_of_prostatic_duct_s1, size: 34
INFO [2025-06-19 20:10:53] -processing cell_group_name: basal_epithelial_cell_of_prostatic_duct.basal_epithelial_cell_of_prostatic_duct_s2, size: 17
INFO [2025-06-19 20:10:54] -processing cell_group_name: basal_epithelial_cell_of_prostatic_duct.basal_epithelial_cell_of_prostatic_duct_s4, size: 14
INFO [2025-06-19 20:10:55] -processing cell_group_name: basal_epithelial_cell_of_prostatic_duct.basal_epithelial_cell_of_prostatic_duct_s5, size: 11
INFO [2025-06-19 20:10:56] -processing cell_group_name: basal_epithelial_cell_of_prostatic_duct.basal_epithelial_cell_of_prostatic_duct_s6, size: 7
INFO [2025-06-19 20:10:56] -processing cell_group_name: basal_epithelial_cell_of_prostatic_duct.basal_epithelial_cell_of_prostatic_duct_s7, size: 3
INFO [2025-06-19 20:10:57] -processing cell_group_name: basal_epithelial_cell_of_prostatic_duct.basal_epithelial_cell_of_prostatic_duct_s8, size: 1
INFO [2025-06-19 20:10:58] -writing cell clusters file: /Users/ugursahin/ProstateCancerEvo_SpatialAnalysis/samples/R1/CNA/17_HMM_predHMMi6.leiden.hmm_mode-subclusters.cell_groupings
INFO [2025-06-19 20:10:58] -writing cnv regions file: /Users/ugursahin/ProstateCancerEvo_SpatialAnalysis/samples/R1/CNA/17_HMM_predHMMi6.leiden.hmm_mode-subclusters.pred_cnv_regions.dat
INFO [2025-06-19 20:10:58] -writing per-gene cnv report: /Users/ugursahin/ProstateCancerEvo_SpatialAnalysis/samples/R1/CNA/17_HMM_predHMMi6.leiden.hmm_mode-subclusters.pred_cnv_genes.dat
INFO [2025-06-19 20:10:58] -writing gene ordering info: /Users/ugursahin/ProstateCancerEvo_SpatialAnalysis/samples/R1/CNA/17_HMM_predHMMi6.leiden.hmm_mode-subclusters.genes_used.dat
INFO [2025-06-19 20:11:00] ::plot_cnv:Start
INFO [2025-06-19 20:11:00] ::plot_cnv:Current data dimensions (r,c)=2632,695 Total=5540366 Min=2 Max=6.
INFO [2025-06-19 20:11:00] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2025-06-19 20:11:00] plot_cnv_observation:Start
INFO [2025-06-19 20:11:00] Observation data size: Cells= 185 Genes= 2632
INFO [2025-06-19 20:11:00] plot_cnv_observation:Writing observation groupings/color.
INFO [2025-06-19 20:11:00] plot_cnv_observation:Done writing observation groupings/color.
INFO [2025-06-19 20:11:00] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2025-06-19 20:11:00] plot_cnv_observation:Done writing observation heatmap thresholds.
INFO [2025-06-19 20:11:00] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2025-06-19 20:11:00] Quantiles of plotted data range: 2,3,3,3,5
INFO [2025-06-19 20:11:00] plot_cnv_references:Start
INFO [2025-06-19 20:11:00] Reference data size: Cells= 510 Genes= 2632
INFO [2025-06-19 20:11:00] plot_cnv_references:Number reference groups= 2
INFO [2025-06-19 20:11:00] plot_cnv_references:Plotting heatmap.
INFO [2025-06-19 20:11:00] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2025-06-19 20:11:00] Quantiles of plotted data range: 2,3,3,3,6
INFO [2025-06-19 20:11:00]

	STEP 18: Run Bayesian Network Model on HMM predicted CNVs

INFO [2025-06-19 20:11:00] Creating the following Directory:  /Users/ugursahin/ProstateCancerEvo_SpatialAnalysis/samples/R1/CNA/BayesNetOutput.HMMi6.leiden.hmm_mode-subclusters
INFO [2025-06-19 20:11:00] Initializing new MCM InferCNV Object.
INFO [2025-06-19 20:11:00] validating infercnv_obj
INFO [2025-06-19 20:11:00] Total CNV's:  196
INFO [2025-06-19 20:11:00] Loading BUGS Model.
INFO [2025-06-19 20:11:00] Running Sampling Using Parallel with  4 Cores
INFO [2025-06-19 20:11:31] Obtaining probabilities post-sampling
INFO [2025-06-19 20:11:36] Gibbs sampling time:  0.59207858244578  Minutes
INFO [2025-06-19 20:11:40] ::plot_cnv:Start
INFO [2025-06-19 20:11:40] ::plot_cnv:Current data dimensions (r,c)=2632,695 Total=121690.574046238 Min=0 Max=0.989927234558799.
INFO [2025-06-19 20:11:40] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2025-06-19 20:11:40] plot_cnv_observation:Start
INFO [2025-06-19 20:11:40] Observation data size: Cells= 185 Genes= 2632
INFO [2025-06-19 20:11:40] plot_cnv_observation:Writing observation groupings/color.
INFO [2025-06-19 20:11:40] plot_cnv_observation:Done writing observation groupings/color.
INFO [2025-06-19 20:11:40] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2025-06-19 20:11:40] plot_cnv_observation:Done writing observation heatmap thresholds.
INFO [2025-06-19 20:11:40] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2025-06-19 20:11:40] Quantiles of plotted data range: 0,0,0,0.668324418328167,0.989927234558799
INFO [2025-06-19 20:11:40] plot_cnv_references:Start
INFO [2025-06-19 20:11:40] Reference data size: Cells= 510 Genes= 2632
INFO [2025-06-19 20:11:40] plot_cnv_references:Number reference groups= 2
INFO [2025-06-19 20:11:40] plot_cnv_references:Plotting heatmap.
INFO [2025-06-19 20:11:40] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2025-06-19 20:11:40] Quantiles of plotted data range: 0,0,0,0,0.889130468691603
INFO [2025-06-19 20:11:44]

	STEP 19: Filter HMM predicted CNVs based on the Bayesian Network Model results and BayesMaxPNormal

INFO [2025-06-19 20:11:44] Attempting to removing CNV(s) with a probability of being normal above  0.5
INFO [2025-06-19 20:11:44] Removing  2  CNV(s) identified by the HMM.
INFO [2025-06-19 20:11:44] Total CNV's after removing:  194
INFO [2025-06-19 20:11:44] Reassigning CNVs based on state probabilities.
INFO [2025-06-19 20:11:44] Changing the following CNV's states assigned by the HMM to the following based on the CNV's state probabilities.
 7-region_126 : 4  (P= 0.359093582985784 ) ->  3 (P= 0.360631665093472 )
10-region_133 : 2  (P= 0.401580991446326 ) ->  3 (P= 0.438828335781642 )
22-region_145 : 4  (P= 0.304101348888555 ) ->  3 (P= 0.454538183829775 )
Y-region_184 : 4  (P= 0.22878804687639 ) ->  5 (P= 0.233275939599614 )
2-region_192 : 4  (P= 0.247284465533094 ) ->  3 (P= 0.250558984567257 )
3-region_194 : 4  (P= 0.247284465533094 ) ->  3 (P= 0.250558984567257 )
X-region_204 : 2  (P= 0.247647233823492 ) ->  3 (P= 0.24965922909167 )
17-region_217 : 4  (P= 0.249003068911878 ) ->  3 (P= 0.251706349663048 )
18-region_222 : 4  (P= 0.124378170199924 ) ->  3 (P= 0.248850120767422 )
20-region_224 : 4  (P= 0.249003068911878 ) ->  3 (P= 0.251706349663048 )
2-region_674 : 4  (P= 0.124431566243867 ) ->  5 (P= 0.250138305856751 )
8-region_681 : 4  (P= 0.122475797411329 ) ->  5 (P= 0.251894912226925 )
21-region_698 : 4  (P= 0.122475797411329 ) ->  5 (P= 0.251894912226925 )
Y-region_840 : 6  (P= 0.11975141973314 ) ->  5 (P= 0.352265802118824 )
13-region_857 : 4  (P= 0.234975955747081 ) ->  3 (P= 0.3054605853856 )
INFO [2025-06-19 20:11:44] Creating Plots for CNV and cell Probabilities.
INFO [2025-06-19 20:12:12] ::plot_cnv:Start
INFO [2025-06-19 20:12:12] ::plot_cnv:Current data dimensions (r,c)=2632,695 Total=121256.373962523 Min=0 Max=0.989927234558799.
INFO [2025-06-19 20:12:12] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2025-06-19 20:12:12] plot_cnv_observation:Start
INFO [2025-06-19 20:12:12] Observation data size: Cells= 185 Genes= 2632
INFO [2025-06-19 20:12:12] plot_cnv_observation:Writing observation groupings/color.
INFO [2025-06-19 20:12:12] plot_cnv_observation:Done writing observation groupings/color.
INFO [2025-06-19 20:12:12] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2025-06-19 20:12:12] plot_cnv_observation:Done writing observation heatmap thresholds.
INFO [2025-06-19 20:12:12] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2025-06-19 20:12:12] Quantiles of plotted data range: 0,0,0,0.668324418328167,0.989927234558799
INFO [2025-06-19 20:12:12] plot_cnv_references:Start
INFO [2025-06-19 20:12:12] Reference data size: Cells= 510 Genes= 2632
INFO [2025-06-19 20:12:13] plot_cnv_references:Number reference groups= 2
INFO [2025-06-19 20:12:13] plot_cnv_references:Plotting heatmap.
INFO [2025-06-19 20:12:13] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2025-06-19 20:12:13] Quantiles of plotted data range: 0,0,0,0,0.889130468691603
INFO [2025-06-19 20:12:15] ::plot_cnv:Start
INFO [2025-06-19 20:12:15] ::plot_cnv:Current data dimensions (r,c)=2632,695 Total=5537965 Min=2 Max=5.
INFO [2025-06-19 20:12:15] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2025-06-19 20:12:15] plot_cnv_observation:Start
INFO [2025-06-19 20:12:15] Observation data size: Cells= 185 Genes= 2632
INFO [2025-06-19 20:12:15] plot_cnv_observation:Writing observation groupings/color.
INFO [2025-06-19 20:12:15] plot_cnv_observation:Done writing observation groupings/color.
INFO [2025-06-19 20:12:15] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2025-06-19 20:12:15] plot_cnv_observation:Done writing observation heatmap thresholds.
INFO [2025-06-19 20:12:15] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2025-06-19 20:12:15] Quantiles of plotted data range: 2,3,3,3,5
INFO [2025-06-19 20:12:15] plot_cnv_references:Start
INFO [2025-06-19 20:12:15] Reference data size: Cells= 510 Genes= 2632
INFO [2025-06-19 20:12:15] plot_cnv_references:Number reference groups= 2
INFO [2025-06-19 20:12:15] plot_cnv_references:Plotting heatmap.
INFO [2025-06-19 20:12:15] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2025-06-19 20:12:15] Quantiles of plotted data range: 2,3,3,3,5
INFO [2025-06-19 20:12:15]

	STEP 20: Converting HMM-based CNV states to repr expr vals

INFO [2025-06-19 20:12:17] ::plot_cnv:Start
INFO [2025-06-19 20:12:17] ::plot_cnv:Current data dimensions (r,c)=2632,695 Total=1854362.5 Min=0.5 Max=2.
INFO [2025-06-19 20:12:17] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2025-06-19 20:12:17] plot_cnv_observation:Start
INFO [2025-06-19 20:12:17] Observation data size: Cells= 185 Genes= 2632

In [34]:
infercnv_obj